version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
     - DATABASE_HOST=172.19.0.2
     - POSTGRES_DB=test-master-dev
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=adminpassword
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres